/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedThongKeRouteImport } from './routes/_authenticated/thong-ke'
import { Route as AuthenticatedLopHocRouteImport } from './routes/_authenticated/lop-hoc'
import { Route as AuthenticatedKhoaHocRouteImport } from './routes/_authenticated/khoa-hoc'
import { Route as AuthenticatedHocVienRouteImport } from './routes/_authenticated/hoc-vien'
import { Route as AuthenticatedHocPhiRouteImport } from './routes/_authenticated/hoc-phi'
import { Route as AuthenticatedGiaoVienRouteImport } from './routes/_authenticated/giao-vien'
import { Route as AuthenticatedGhiDanhRouteImport } from './routes/_authenticated/ghi-danh'
import { Route as AuthenticatedDiemDanhRouteImport } from './routes/_authenticated/diem-danh'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedThongKeRoute = AuthenticatedThongKeRouteImport.update({
  id: '/thong-ke',
  path: '/thong-ke',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLopHocRoute = AuthenticatedLopHocRouteImport.update({
  id: '/lop-hoc',
  path: '/lop-hoc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKhoaHocRoute = AuthenticatedKhoaHocRouteImport.update({
  id: '/khoa-hoc',
  path: '/khoa-hoc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHocVienRoute = AuthenticatedHocVienRouteImport.update({
  id: '/hoc-vien',
  path: '/hoc-vien',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHocPhiRoute = AuthenticatedHocPhiRouteImport.update({
  id: '/hoc-phi',
  path: '/hoc-phi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGiaoVienRoute = AuthenticatedGiaoVienRouteImport.update({
  id: '/giao-vien',
  path: '/giao-vien',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGhiDanhRoute = AuthenticatedGhiDanhRouteImport.update({
  id: '/ghi-danh',
  path: '/ghi-danh',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiemDanhRoute = AuthenticatedDiemDanhRouteImport.update({
  id: '/diem-danh',
  path: '/diem-danh',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/diem-danh': typeof AuthenticatedDiemDanhRoute
  '/ghi-danh': typeof AuthenticatedGhiDanhRoute
  '/giao-vien': typeof AuthenticatedGiaoVienRoute
  '/hoc-phi': typeof AuthenticatedHocPhiRoute
  '/hoc-vien': typeof AuthenticatedHocVienRoute
  '/khoa-hoc': typeof AuthenticatedKhoaHocRoute
  '/lop-hoc': typeof AuthenticatedLopHocRoute
  '/thong-ke': typeof AuthenticatedThongKeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/diem-danh': typeof AuthenticatedDiemDanhRoute
  '/ghi-danh': typeof AuthenticatedGhiDanhRoute
  '/giao-vien': typeof AuthenticatedGiaoVienRoute
  '/hoc-phi': typeof AuthenticatedHocPhiRoute
  '/hoc-vien': typeof AuthenticatedHocVienRoute
  '/khoa-hoc': typeof AuthenticatedKhoaHocRoute
  '/lop-hoc': typeof AuthenticatedLopHocRoute
  '/thong-ke': typeof AuthenticatedThongKeRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/diem-danh': typeof AuthenticatedDiemDanhRoute
  '/_authenticated/ghi-danh': typeof AuthenticatedGhiDanhRoute
  '/_authenticated/giao-vien': typeof AuthenticatedGiaoVienRoute
  '/_authenticated/hoc-phi': typeof AuthenticatedHocPhiRoute
  '/_authenticated/hoc-vien': typeof AuthenticatedHocVienRoute
  '/_authenticated/khoa-hoc': typeof AuthenticatedKhoaHocRoute
  '/_authenticated/lop-hoc': typeof AuthenticatedLopHocRoute
  '/_authenticated/thong-ke': typeof AuthenticatedThongKeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diem-danh'
    | '/ghi-danh'
    | '/giao-vien'
    | '/hoc-phi'
    | '/hoc-vien'
    | '/khoa-hoc'
    | '/lop-hoc'
    | '/thong-ke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/diem-danh'
    | '/ghi-danh'
    | '/giao-vien'
    | '/hoc-phi'
    | '/hoc-vien'
    | '/khoa-hoc'
    | '/lop-hoc'
    | '/thong-ke'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/diem-danh'
    | '/_authenticated/ghi-danh'
    | '/_authenticated/giao-vien'
    | '/_authenticated/hoc-phi'
    | '/_authenticated/hoc-vien'
    | '/_authenticated/khoa-hoc'
    | '/_authenticated/lop-hoc'
    | '/_authenticated/thong-ke'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/thong-ke': {
      id: '/_authenticated/thong-ke'
      path: '/thong-ke'
      fullPath: '/thong-ke'
      preLoaderRoute: typeof AuthenticatedThongKeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lop-hoc': {
      id: '/_authenticated/lop-hoc'
      path: '/lop-hoc'
      fullPath: '/lop-hoc'
      preLoaderRoute: typeof AuthenticatedLopHocRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/khoa-hoc': {
      id: '/_authenticated/khoa-hoc'
      path: '/khoa-hoc'
      fullPath: '/khoa-hoc'
      preLoaderRoute: typeof AuthenticatedKhoaHocRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hoc-vien': {
      id: '/_authenticated/hoc-vien'
      path: '/hoc-vien'
      fullPath: '/hoc-vien'
      preLoaderRoute: typeof AuthenticatedHocVienRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hoc-phi': {
      id: '/_authenticated/hoc-phi'
      path: '/hoc-phi'
      fullPath: '/hoc-phi'
      preLoaderRoute: typeof AuthenticatedHocPhiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/giao-vien': {
      id: '/_authenticated/giao-vien'
      path: '/giao-vien'
      fullPath: '/giao-vien'
      preLoaderRoute: typeof AuthenticatedGiaoVienRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ghi-danh': {
      id: '/_authenticated/ghi-danh'
      path: '/ghi-danh'
      fullPath: '/ghi-danh'
      preLoaderRoute: typeof AuthenticatedGhiDanhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diem-danh': {
      id: '/_authenticated/diem-danh'
      path: '/diem-danh'
      fullPath: '/diem-danh'
      preLoaderRoute: typeof AuthenticatedDiemDanhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDiemDanhRoute: typeof AuthenticatedDiemDanhRoute
  AuthenticatedGhiDanhRoute: typeof AuthenticatedGhiDanhRoute
  AuthenticatedGiaoVienRoute: typeof AuthenticatedGiaoVienRoute
  AuthenticatedHocPhiRoute: typeof AuthenticatedHocPhiRoute
  AuthenticatedHocVienRoute: typeof AuthenticatedHocVienRoute
  AuthenticatedKhoaHocRoute: typeof AuthenticatedKhoaHocRoute
  AuthenticatedLopHocRoute: typeof AuthenticatedLopHocRoute
  AuthenticatedThongKeRoute: typeof AuthenticatedThongKeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDiemDanhRoute: AuthenticatedDiemDanhRoute,
  AuthenticatedGhiDanhRoute: AuthenticatedGhiDanhRoute,
  AuthenticatedGiaoVienRoute: AuthenticatedGiaoVienRoute,
  AuthenticatedHocPhiRoute: AuthenticatedHocPhiRoute,
  AuthenticatedHocVienRoute: AuthenticatedHocVienRoute,
  AuthenticatedKhoaHocRoute: AuthenticatedKhoaHocRoute,
  AuthenticatedLopHocRoute: AuthenticatedLopHocRoute,
  AuthenticatedThongKeRoute: AuthenticatedThongKeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
